### ISSUE TITLE
Can't load Geld-Api on my Minecraft Server

### ISSUE THREAD

**Issue by itsLucky6211** [Senne98/Geld-API#1]
I have a CraftBukkit 1.20.1 Server, and whenever i try to load it in my server along with a plugin that needs Geld-API to function the Console says "Could not load 'plugins\Geld-API-2.0-SNAPSHOT.jar' in folder 'plugins'"
i've downloaded Geld-API from https://dev.bukkit.org/projects/geld-api/files/4594630 .
Can anyone help me?

**Comment by Senne98** [comment]
Geld Api is made for papermc, and I probably doesn't work with craftbukkit. You can change your server to papermc if you want to use it. All craftbukkit plugins should work on papermc, but not the other way around. Papermc is also more performace focussed.
